org: thanh172
app: serverless-test
service: myserverlessproject3

provider:
  name: aws
  runtime: nodejs12.x
  profile: thanhdev172
  region: ap-southeast-1
  stage: files
  environment:
    imageUploadBucket: ${self:custom.imageUploadBucket}
    region: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
        - ses:*
      Resource: "*"

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  imageUploadBucket: my-image-upload-bucket-demo-sws-17
  s3Sync:
    - imageUploadBucket: ${self:custom.imageUploadBucket}
      localDir: uploadData

functions:
  imageUpload:
    handler: lambdas/endpoints/uploadImage.handler
    events:
      - http:
          path: upload
          method: POST
          cors: true
  getImages:
    handler: lambdas/endpoints/getImages.handler
    events:
      - http:
          path: /
          method: GET
          cors: true
  deleteImages:
    handler: lambdas/endpoints/deleteImage.handler
    events:
      - http:
          path: /{name}
          method: DELETE
          cors: true

resources:
  Resources:
    ImageUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.imageUploadBucket}
        AccessControl: PublicRead
